# Generated by Django 5.1.6 on 2025-06-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DifferentSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('pname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('wnumber', models.CharField(max_length=15)),
                ('pnumber', models.CharField(max_length=15)),
                ('cmode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Online', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DifferentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='DifferentExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exams')),
            ],
        ),
        migrations.CreateModel(
            name='PopularCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('popcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentcourses')),
            ],
        ),
        migrations.CreateModel(
            name='PopularExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('popexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentexams')),
            ],
        ),
        migrations.CreateModel(
            name='PopularSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('popsub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentsubjects')),
            ],
        ),
        migrations.AddField(
            model_name='differentsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjects'),
        ),
        migrations.CreateModel(
            name='ToprelatedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('topecourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentcourses')),
            ],
        ),
        migrations.CreateModel(
            name='ToprelatedExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('topexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentexams')),
            ],
        ),
        migrations.CreateModel(
            name='ToprelatedSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='images/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='images')),
                ('topsub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.differentsubjects')),
            ],
        ),
        migrations.CreateModel(
            name='Downloadmaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pop_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.popularsubjects')),
                ('top_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.toprelatedsubjects')),
            ],
        ),
    ]
